/**
 * HairTransplant APIS
 * API DOCUMENTATION
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonalInformation } from './personalInformation';


export interface ClientVisit { 
    id?: number;
    personalInformation?: PersonalInformation;
    salesperson?: string;
    salesManager?: string;
    visitDate?: string;
}

