/**
 * HairTransplant APIS
 * API DOCUMENTATION
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonalInformation } from './personalInformation';


export interface LifeStyle { 
    id?: number;
    personalInformation?: PersonalInformation;
    diet?: string;
    exercise?: string;
    alcohol?: LifeStyle.AlcoholEnum;
    tobacco?: LifeStyle.TobaccoEnum;
    dateDataEntry?: string;
    idParent?:string;
}
export namespace LifeStyle {
    export type AlcoholEnum = 'YES' | 'NO';
    export const AlcoholEnum = {
        Yes: 'YES' as AlcoholEnum,
        No: 'NO' as AlcoholEnum
    };
    export type TobaccoEnum = 'YES' | 'NO';
    export const TobaccoEnum = {
        Yes: 'YES' as TobaccoEnum,
        No: 'NO' as TobaccoEnum
    };
}


