/**
 * HairTransplant APIS
 * API DOCUMENTATION
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MedicalHistory { 
    id?: number;
    preExistingConditions?: string;
    currentMedications?: string;
    allergies?: string;
    previousTransplants?: string;
    dateDataEntry?: string;
    parent?: string;
    stringParent?: string;
    idParent?: string;
}

